# Copyright (C) 2024 Eternilab <support@eternilab.com>
#
# SPDX-License-Identifier: CECILL-2.1

---
- name: "Get SSHFP records"
  ansible.builtin.command: "ssh-keygen -r {{ inventory_hostname }}."
  register: sshfp_entries
  changed_when: false

- name: "Debug SSHFP"
  ansible.builtin.debug:
    msg: "{{ hostvars[inventory_hostname].sshfp_entries.stdout_lines }}"
