# Copyright (C) 2024 Eternilab <support@eternilab.com>
#
# SPDX-License-Identifier: CECILL-2.1

---
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
